### ISSUE TITLE
Fine grained warning control settings

### ISSUE THREAD

**Issue by nebomuk** [hakaishi/shutdown-qapps#14]
This feature tries to resolve the issue that QShutdown is sending out too many warning notifications, even when it is just running in the background and no countdown has been configured. 

Implement separate settings instead of a single setting to enable warnings for:
1.) Countdown not running after the countdown has been configured
2.) Countdown close to zero - shutdown action immediate

In case of 1.) The warning should only appear after the countdown has been configured. The warning should not appear if the app is just minimized and there was no user action. 
For example, the app should not pop into the foreground and display warnings immediately after the system has been restored from a previous hibernate or suspend state and QShutdown is still running, but there was no user interaction. 

Maybe the settings for warning 1.) could be moved to the app settings instead of the main screen?

**Comment by hakaishi** [comment]
There are two events for pop up and/or tray icon message:  
1. The application waiting for the user to start a countdown (there is no such thing as a state of count down being configured or not)
2. The immediacy of the selected action to be executed (eg. shutdown).

Right now you can only disable this either completely or not.  I haven't considered the case that someone might want the application to run without starting the countdown. For this use case it might be indeed annoying if the app constantly reminds the user to start the countdown again.

My suggestion is to add another option in the preferences window to disable bugging the user to start the countdown.

If this fits you use case, I could implement this feature. How about it?
