### ISSUE TITLE
Problem when countdown is across the midnight (and proposed patch).

### ISSUE THREAD

**Issue by betarho** [hakaishi/shutdown-qapps#7]
Hello,
the expected event after the countdown is not executed when setting a countdown across the midnight. As an example, the problem can be seen setting a countdown time of 5 minutes at 23:58:00.
I think I found the problem.
Please find attached the proposed solution.

[utc_patch.diff.zip](https://github.com/hakaishi/shutdown-qapps/files/949751/utc_patch.diff.zip)

**Comment by hakaishi** [comment]
Wow, thanks. I will add your solution.
Hope that I will find time soon. I'm preparing to move to a new apartment and work is quite busy lately. Maybe on next weekend. I will try to do it earlier, but can't promise that.

**Comment by hakaishi** [comment]
Sorry that it took me so long. Could you please check if this fixes your problem? - I went the other way around in order to simplify the code. So instead of making all clearly named with UTC, I renamed the localized ones. Another reason was that all values for calculations should be UTC anyway. This way Qt can save time for the conversion to localized times, since Qt internally only uses UTC and the OS as well.

**Comment by betarho** [comment]
I made some tests and it seems the fixes are working. These are the tests I did:
- time: 20:12; Minutes till shutdown: 2 -> OK
- time: 23:58; Minutes till shutdown: 4 -> OK
- time: 00:02; Shutdown-time: 00:04 -> OK
- time: 23:58; Shutdown-time: 00:02 -> OK

Just another thing you should consider that is present in my patch (not so easy to notice it...). In the file gui.cpp, lines 617 and 618, you have the following:
```
QDateTime futureDateTime10s = futureDateTime;
futureDateTime10s.addSecs(n);
```
These two instruction are ineffective (nothing is added to the ```futureDateTime10s``` variable). In fact, the ```addSecs()``` function returns a ```QDateTime``` instead of adding the time to the instance on which it is called on.
The working replacement should be:
```
QDateTime futureDateTime10s = futureDateTime.addSecs(n);
```
Do you agree?

**Comment by hakaishi** [comment]
Oh my gosh, you are completely right. Just checked the docu.
Kind of missed out that correction of yours, sorry.
I will add that today, if possible (have to go on a small business trip from tomorrow).

**Comment by hakaishi** [comment]
Added the fix. Sorry for the huge delay. Lately I'm getting busier and busier...
I will release it on launchpad in about an hour. The debian release will take more time, so I won't be able to do it today.

**Comment by hakaishi** [comment]
Sorry, I have to update some translations (almost finished though...), so I can't do it today...
I hope to finish everything by next weekend.
